### ISSUE TITLE
Panic: RelativeUrlWithoutBase

### ISSUE THREAD

**Issue by Boscop** [mkralla11/quick_scraper#4]
I'm getting the following panic:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RelativeUrlWithoutBase', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\surf-1.0.3\src\one_off.rs:34:15
stack backtrace:
   0: backtrace::backtrace::trace_unsynchronized
             at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.44\src\backtrace\mod.rs:66
   1: std::sys_common::backtrace::_print_fmt
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:78
   2: std::sys_common::backtrace::_print::{{impl}}::fmt
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:59
   3: core::fmt::write
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libcore\fmt\mod.rs:1052

   4: std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\io\mod.rs:1428
   5: std::sys_common::backtrace::_print
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:62
   6: std::sys_common::backtrace::print
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\sys_common\backtrace.rs:49
   7: std::panicking::default_hook::{{closure}}
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:204

   8: std::panicking::default_hook
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:224

   9: std::panicking::rust_panic_with_hook
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:470

  10: std::panicking::begin_panic_handler
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:378

  11: core::panicking::panic_fmt
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libcore\panicking.rs:85

  12: core::option::expect_none_failed
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libcore\option.rs:1211
  13: core::result::Result<url::Url, url::parser::ParseError>::unwrap
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libcore\result.rs:1003
  14: surf::one_off::get<alloc::string::String*>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\surf-1.0.3\src\one_off.rs:36
  15: quick_crawler::execute::handle_scrape::{{closure}}::{{closure}}::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\execute\mod.rs:241
  16: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  17: futures_util::stream::stream::StreamExt::poll_next_unpin<futures_util::stream::futures_unordered::FuturesUnordered<std::future::GenFuture<generator-0>>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\mod.rs:1184
  18: futures_util::stream::stream::for_each_concurrent::{{impl}}::poll<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<core::slice::Iter<alloc::string::String>>, closure-0>,std::future::GenFuture<generator-0>,closure-1>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\for_each_concurrent.rs:110
  19: core::future::future::{{impl}}::poll
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libcore\future\future.rs:119
  20: std::future::poll_with_tls_context
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  21: quick_crawler::execute::handle_scrape::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\execute\mod.rs:235
  22: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  23: core::future::future::{{impl}}::poll<alloc::boxed::Box<Future>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libcore\future\future.rs:119
  24: std::future::poll_with_tls_context<core::pin::Pin<alloc::boxed::Box<Future>>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  25: quick_crawler::execute::handle_response_logic::{{closure}}::{{closure}}::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\execute\mod.rs:105
  26: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  27: futures_util::stream::futures_unordered::{{impl}}::poll_next<std::future::GenFuture<generator-0>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\futures_unordered\mod.rs:544
  28: futures_util::stream::stream::StreamExt::poll_next_unpin<futures_util::stream::futures_unordered::FuturesUnordered<std::future::GenFuture<generator-0>>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\mod.rs:1184
  29: futures_util::stream::stream::for_each_concurrent::{{impl}}::poll<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<core::slice::Iter<quick_crawler::scrape::Scrape>>, closure-0>,std::future::GenFuture<generator-0>,closure-1>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\for_each_concurrent.rs:110
  30: std::future::poll_with_tls_context<futures_util::stream::stream::for_each_concurrent::ForEachConcurrent<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<core::slice::Iter<quick_crawler::scrape::Scrape>>, closure-0>, std::future::Gen
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  31: quick_crawler::execute::handle_response_logic::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\execute\mod.rs:102
  32: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  33: std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  34: quick_crawler::execute::execute_deep_scrape::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\execute\mod.rs:87
  35: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  36: std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  37: quick_crawler::dispatch::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\lib.rs:399
  38: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  39: std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  40: quick_crawler::{{impl}}::process::{{closure}}::{{closure}}::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\lib.rs:422
  41: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  42: futures_util::stream::futures_unordered::{{impl}}::poll_next<std::future::GenFuture<generator-0>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\futures_unordered\mod.rs:544
  43: futures_util::stream::stream::StreamExt::poll_next_unpin<futures_util::stream::futures_unordered::FuturesUnordered<std::future::GenFuture<generator-0>>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\mod.rs:1184
  44: futures_util::stream::stream::for_each_concurrent::{{impl}}::poll<futures_util::stream::stream::map::Map<futures_util::stream::iter::Iter<core::slice::Iter<quick_crawler::scrape::StartUrl>>, closure-0>,std::future::GenFuture<generator-0>,closure-1>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\stream\stream\for_each_concurrent.rs:110
  45: core::future::future::{{impl}}::poll<alloc::boxed::Box<Future>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libcore\future\future.rs:119
  46: std::future::poll_with_tls_context<core::pin::Pin<alloc::boxed::Box<Future>>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  47: quick_crawler::{{impl}}::process::{{closure}}::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\lib.rs:437
  48: std::future::{{impl}}::poll<generator-2>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  49: futures_util::future::maybe_done::{{impl}}::poll<std::future::GenFuture<generator-2>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\future\maybe_done.rs:96
  50: futures_util::future::join::{{impl}}::poll<core::pin::Pin<alloc::boxed::Box<Future>>,std::future::GenFuture<generator-2>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\futures-util-0.3.4\src\future\join.rs:55
  51: std::future::poll_with_tls_context<futures_util::future::join::Join<core::pin::Pin<alloc::boxed::Box<Future>>, std::future::GenFuture<generator-2>>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  52: quick_crawler::{{impl}}::process::{{closure}}
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\quick_crawler-0.1.0\src\lib.rs:445
  53: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  54: std::future::poll_with_tls_context<std::future::GenFuture<generator-0>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  55: dlmidi::main::{{closure}}
             at .\src\main.rs:71
  56: std::future::{{impl}}::poll<generator-1>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  57: std::future::poll_with_tls_context<std::future::GenFuture<generator-1>>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:101
  58: async_std::task::block_on::block_on::{{closure}}<std::future::GenFuture<generator-1>,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\block_on.rs:68
  59: std::future::{{impl}}::poll<generator-0>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\future.rs:43
  60: async_std::task::block_on::run::{{closure}}<std::future::GenFuture<generator-0>,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\block_on.rs:128
  61: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<alloc::sync::Arc<crossbeam_utils::sync::parker::Parker>>>>::try_with<core::cell::Cell<core::option::Option<alloc::sync::Arc<crossbeam_utils::sync::parker::Parker>>>,closure-0,core::result:
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\thread\local.rs:262
  62: std::thread::local::LocalKey<core::cell::Cell<core::option::Option<alloc::sync::Arc<crossbeam_utils::sync::parker::Parker>>>>::with<core::cell::Cell<core::option::Option<alloc::sync::Arc<crossbeam_utils::sync::parker::Parker>>>,closure-0,core::result::Res
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\thread\local.rs:239
  63: async_std::task::block_on::run<std::future::GenFuture<generator-0>,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\block_on.rs:118
  64: async_std::task::block_on::block_on::{{closure}}<std::future::GenFuture<generator-1>,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\block_on.rs:72
  65: async_std::task::task::{{impl}}::set_current::{{closure}}<closure-1,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\task.rs:129
  66: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task::Task*>>::try_with<core::cell::Cell<const async_std::task::task::Task*>,closure-0,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCraw
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\thread\local.rs:262
  67: std::thread::local::LocalKey<core::cell::Cell<const async_std::task::task::Task*>>::with<core::cell::Cell<const async_std::task::task::Task*>,closure-0,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerE
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\thread\local.rs:239
  68: async_std::task::task::Task::set_current<closure-1,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\task.rs:124
  69: async_std::task::block_on::block_on<std::future::GenFuture<generator-1>,core::result::Result<alloc::vec::Vec<quick_crawler::DataFromScraperValue>, quick_crawler::QuickCrawlerError>>
             at C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\async-std-1.5.0\src\task\block_on.rs:72
  70: dlmidi::main
             at .\src\main.rs:71
  71: std::rt::lang_start::{{closure}}<()>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\rt.rs:67
  72: std::rt::lang_start_internal::{{closure}}
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\rt.rs:52
  73: std::panicking::try::do_call<closure-0,i32>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:303

  74: panic_abort::__rust_maybe_catch_panic
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libpanic_abort\lib.rs:30
  75: std::panicking::try
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panicking.rs:281

  76: std::panic::catch_unwind
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\panic.rs:394
  77: std::rt::lang_start_internal
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\/src\libstd\rt.rs:51
  78: std::rt::lang_start<()>
             at /rustc/5d04ce67fd14538d03fa47a2598f80d49fd564c6\src\libstd\rt.rs:67
  79: main
  80: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  81: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  82: BaseThreadInitThunk
  83: RtlUserThreadStart
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

https://doc.servo.org/url/index.html#base-url

Maybe something is not working with the way this crawler joins relative urls onto the parent url?

Btw, the html in this case is like:
```html
<a href="foo-bar">Foo Bar</a>
```

**Comment by mkralla11** [comment]
Hi @Boscop! 

Relative urls are not yet supported. 

...but I just worked on a pretty large refactor under-the-hood to support your request because I'm happy you are using the library 😄 

Basically, in order to support relative _and_ absolute paths (without scheme/domain/port,etc), I have to track the previous url for which the last html was returned from (where as prior, I had no reason to do so). I think this is a pretty important feature request so I got right on it. I also confirmed in the test that it does work (I didn't specifically test href="foo-bar", but instead href="../foo/bar" because it seemed a little more challenging and I wanted to prove it works).

I've made a PR for this feature and I'll merge now, then publish a bumped version for the crate. Once all is complete, please let me know if you run into any more issues.

#5
